apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
  labels:
    name: {{.Values.service.name}}
spec:
  type: "{{.Values.service.type}}"
  ports:
  - name: http
    port: {{.Values.service.port}}
    targetPort: {{.Values.service.port}}
  selector:
    app: {{.Values.deploy.name}}